/**
 * @copyright 2026
 * @author Rohanul Haque Rohan - MERN Stack Developer
 * @license Apache-2.0
 */

/**
 * Next.js Module
 */
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

/**
 * Components
 */
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/sonner";

/**
 * CSS
 */
import "./globals.css";

/**
 * Google Fonts Configuration
 */
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

/**
 * Metadata
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout Component
 * @param children - The child components to be rendered
 * @returns The root layout component
 */
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${outfit.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
